phases:
- template: /eng/build.yml
  parameters:
    phaseName: Windows
    agentOs: Windows_NT
    buildReason: Internal
    queue: 
      name: DotNetCore-Build
      demands:
        - agent.os -equals Windows_NT
      parallel: 2
      matrix:
        Build_Debug:
          _BuildConfig: Debug
          _BuildArch: x64
          _PublishType: none
          _SignType: test
        Build_Release:
          _BuildConfig: Release
          _BuildArch: x64
          _PublishType: none
          _SignType: real

- template: /eng/build.yml
  parameters:
    phaseName: CentOS_7
    agentOs: Linux
    buildReason: Internal
    dockerImage: microsoft/dotnet-buildtools-prereqs:centos-7-c103199-20180628120549
    queue:
      name: DotNet-Build
      demands:
        - agent.os -equals Linux
      parallel: 2
      matrix:
        Build_Debug:
          _BuildConfig: Debug
          _BuildArch: x64
          _PublishType: none
          _SignType: test
        Build_Release:
          _BuildConfig: Release
          _BuildArch: x64
          _PublishType: none
          _SignType: real

- template: /eng/build.yml
  parameters:
    phaseName: Ubuntu_14_04
    agentOs: Linux
    buildReason: Internal
    dockerImage: microsoft/dotnet-buildtools-prereqs:ubuntu-18.04-c103199-20180628134610
    queue:
      name: DotNet-Build
      demands:
        - agent.os -equals Linux
      matrix:
        Build_Release:
          _BuildConfig: Release
          _BuildArch: x64
          _PublishType: none
          _SignType: real

- template: /eng/build.yml
  parameters:
    phaseName: MacOS
    agentOs: Darwin
    buildReason: Internal
    queue: 
      name: DotNetCore-Build
      demands:
        - agent.os -equals Darwin
      parallel: 2
      matrix:
        Build_Debug:
          _BuildConfig: Debug
          _BuildArch: x64
          _PublishType: none
          _SignType: test
        Build_Release:
          _BuildConfig: Release
          _BuildArch: x64
          _PublishType: none
          _SignType: real

